version: "3.8"

services:
  app:
    restart: always
    build:
      context: app
      dockerfile: ../dockerfiles/app.Dockerfile
    ports:
      - 4173:4173
    depends_on:
      - controller
    networks:
      - stupid_network
    env:
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
      - TIMEZONE=${TIMEZONE}

  worker:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/worker.Dockerfile
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
      - "/dev/gpiochip0:/dev/gpiochip0"
    depends_on:
      - controller
    networks:
      - stupid_network

  controller:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/controller.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - stupid_network

  redis:
    restart: always
    image: redis/redis-stack-server:latest
    networks:
      - stupid_network
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379 # for sneaky access

networks:
  stupid_network:
    driver: bridge

volumes:
  redis_data:
