version: '3.8'

services:
  app:
    build:
      context: ../app
      dockerfile: app.Dockerfile
    ports:
      - "4173:4173"

  controller:
    build:
      context: ../controller
      dockerfile: controller.Dockerfile
    ports:
      - "8080:8080"