version: "3.8"

services:
  app:
    build:
      context: app
      dockerfile: ../dockerfiles/app.Dockerfile
    ports:
      - 4173:4173
    depends_on:
      - controller
    networks:
      - stupid_network

  worker:
    build:
      context: .
      dockerfile: dockerfiles/worker.Dockerfile
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    depends_on:
      - controller
    networks:
      - stupid_network

  controller:
    build:
      context: .
      dockerfile: dockerfiles/controller.Dockerfile
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
    ports:
      - 8080:8080
    depends_on:
      - redis
    networks:
      - stupid_network

  redis:
    image: redis/redis-stack-server:latest
    networks:
      - stupid_network
    environment:
      - REDIS_ARGS=--save 1200 32
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379 # for sneaky access

networks:
  stupid_network:
    driver: bridge

volumes:
  redis_data:
