version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: ../dockerfiles/app.Dockerfile
    network_mode: host

  controller:
    build:
      context: controller
      dockerfile: ../dockerfiles/controller.Dockerfile
    network_mode: host

  worker:
    build:
      context: lettore
      dockerfile: ../dockerfiles/worker.Dockerfile
    network_mode: host